### ISSUE TITLE
Wireframe: newsroom signup

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#140]
After the onboarding (in-person!) session, we [revised the newsroom signup wireframe](https://design.penpot.app/#/view/167be840-9008-11ec-bd38-efdb6fa63305?page-id=7c149280-9ef2-11ec-8243-fb3945d660a4&section=interactions&index=0&share-id=dd36ab10-a9f2-11ec-a0b4-765163de8d2d) to include a field for the logo and alternative payment methods.  
Switch to page two, in the link above, to see the first signup wireframe :)

![image](https://user-images.githubusercontent.com/122730/159556315-557d3522-b9f9-45f9-96f0-21866388a14a.png)

**Comment by wpf500** [comment]
Looks good I think, although in practice the taking payment details bit will probably just be a credit card I think

I think we'll need to mention somewhere in the your-organisation.beabee.io bit that the user can also set their own domain later, but I guess that's more for the design bit

**Comment by aiscarvalho** [comment]
We added alternative payment options because Tobias explained that in Germany media orgs couldn't have cards associated to their bank accounts.

As an alternative, we could display just the card payment interface and offer a link to access alternative payment methods (example: Prefer to pay by direct debit?). If we can have the browser do some location work, we can show a sensible default for payment to German based users.

**Comment by saschafoerster** [comment]
Maybe also think of plugins, that might add other payment methods later on. 
I like this overview of possible extensions: https://marketplace.pretix.eu/categories/2/

**Comment by wpf500** [comment]
Hey @saschafoerster, what a list of payment gateways! We're definitely aiming towards this sort of thing in the future, with Stripe being the first one we'll do. I'm hoping the process of adding a second payment gateway will help inform what payment gateway plugins could look like, so one day we can have docs on how to create them

**Comment by saschafoerster** [comment]
I think the most important thing here is to make it modular, so that any kind of payment plugin created by community, company our you, can be turned on and off, as every company has different target groups. It gets even more important for internationalisation. GoCardless is not well known in Germany so people prefer to use different methods. For Germany it's PayPal, bank transfer, SEPA and only then credit cards (mostly VISA and MasterCard). Rechnung and manual payment would be nice as well. :) Leave the rest to the community to develop. 😂
