### ISSUE TITLE
Spec: Multiple payment methods UI/UX (join flow)

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#187]
We updated the first step of the join flow to include multiple payment options and update the order of the content blocks: email and password are now on top; contribution and payment options are together, at the bottom. We added titles along the form to make the blocks clearer.[Spec in Penpot](https://design.penpot.app/#/view/b59ef0e0-cf5e-11eb-abea-1491b30edcfb?page-id=7e4c6780-d12e-11ec-857d-2f3d359d7ad0&section=interactions&index=0&share-id=c3de8010-d13a-11ec-ab9e-75f6b8214121)

Here are two screenshots to show layout variation according to the number of payment options (the last page of the spec details alternate layouts according to the number of options).

![image](https://user-images.githubusercontent.com/122730/167890739-f74dc5c8-1de2-4dc4-be48-9a4e3e94da98.png)

![image](https://user-images.githubusercontent.com/122730/167890800-45262e88-3353-45e7-8fa4-c97169fca15d.png)

How does this look?

**Comment by saschafoerster** [comment]
Love it already. What happens with more than four payment options? Will there be a second line? Can you put a "favorite" payment option to the top/front?

**Comment by wpf500** [comment]
Looks great!

@saschafoerster
* Good question about the more than 4 payment options, @aiscarvalho?
* Admins will be able to choose the order the payment options are shown to the user

**Comment by wpf500** [comment]
Ah sorry I see that the more than 4 options is covered on Penpot
![image](https://user-images.githubusercontent.com/2084823/168025911-964cc160-656e-4ad0-a4db-fd51b525d876.png)

**Comment by wpf500** [comment]
@aiscarvalho is the second step (entering payment details) of the join flow coming in this issue?

**Comment by saschafoerster** [comment]
It's so perfect! 🥰

**Comment by aiscarvalho** [comment]
@wpf500 yes, second step will be in this spec too. We'll post it here when we finish.

@saschafoerster thanks for your comments!

**Comment by TobiasHauswurz** [comment]
Hey, just some notes: 

**Page 1:** 

- There might a reason why Email and Password moved to the top, but I found it nicer the other way round. Not only design wise, but it's also more playful to start with. And the Monthly/Annual-buttons worked great as a divider between the content (headline and subheadline) and the form elements. Maybe it's only me, but the design with payment on top looked much better structured, because it had the eyecatcher on top. Now the eyecatcher is somewhere in the middle, although I (as a User) should start at the top (actually wonder how many people would start to play with the amounts instead of filling in the email address :P) Sorry, too many words, I think my point was clear a while ago...  

- The "Already a member" bit looks a bit lost

- Right now the "Back to Deine Lokalreporter"-Button is currently only used on the Login-Page. Are we using that here now as well or was there a reason why we didn't in the first place?

**Page 2**

- not sure about "Finish" as button text, because there is step 2 coming afterwards

**Comment by wpf500** [comment]
@TobiasHauswurz moving the email and password to the top was actually my suggestion as I thought:

a. it was strange that the contribution amount was separated from the payment method and fee option
b. it was simpler to imagine a flow for signing up without contributing. Currently the one I hacked in for Brush and Bow looks a bit strange

![image](https://user-images.githubusercontent.com/2084823/169096964-0fbb481f-89c5-49c3-8c51-e12779cdf480.png)

However I agree it has lost something a bit "eyecatching" so maybe that was a bad suggestion.

Agreed on the "Back to..." button, I think it should be everywhere

**Comment by aiscarvalho** [comment]
@TobiasHauswurz @wpf500  thanks for the on point feedback!

1. @TobiasHauswurz we agree with your take, having the amount input on the top brings playfulness to the form. At the same time, @wpf500 we understand the logic of grouping together the amount input and payment method (plus solving the join flow case of Brush&Bow).

Maybe for now we keep the current order -- amount input on top -- and re-think the join flow further ahead?
We can save a backlog card to design different join flows such as non-contributing members or one-off donations.

Here's a screenshot with the amount back on top:
![image](https://user-images.githubusercontent.com/122730/169258146-2fa148db-9a22-4f68-aa9f-fbbd15d55a74.png)

2. Agreed, the _already a member_ looks lost in this configuration.

3. 100% agreed! The back button should always be there.

Page 2: good call. We updated the button to "almost done!".

**Comment by saschafoerster** [comment]
Just an short idea. I like forms, that are very simple and on point on the first page. So only: contribution and let's go to the next step. Then a second page of the form, where I can choose, which payment provider I like or login with my existing account (and maybe an already existing connection to a payment provider).  So the focus stays very clear on choosing the contribution and not being overwhelmed by all the options on the first page. This is just an idea. ;)

**Comment by wpf500** [comment]
Hi @saschafoerster, unfortunately because of technical constraints this would actually have to be a three step process (contribution -> payment type -> payment details), as we need to setup the payment form once we know what payment method the user wants to use.

We could get around this constraint by only supporting Stripe, but then we loose the ability to a) use GoCardless (which doesn't necessarily matter for new newsrooms as Stripe also supports direct debit, but does for existing newsrooms) and b) add other payment providers like PayPal in the future.

So I wonder what you think given this constraint? Would you opt for a three step over the two step? Our flow is very similar to The Guardian's [supporter flow](https://support.theguardian.com/uk/contribute) which I think is a good sign as they have lots of UX people to test these things.

**Comment by wpf500** [comment]
Closing this as latest spec has been reviewed
