### ISSUE TITLE
Spec: Callout sharing menu for users

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#188]
![image](https://user-images.githubusercontent.com/159868/167898175-954cb57e-b1ce-405d-9715-599b9cf7a520.png)

We put the most common options in to see what the widget would look like, but it's definitely open for review.

UX-wise, the idea would be for the box to expand from the Share button, but if this turns out to be too onerous, a simple modal can suffice for now.

[See spec on PenPot](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4ac1a360-d117-11ec-b5d3-b772d2e677f5&section=interactions&index=0&share-id=9cf45690-d145-11ec-ab9e-75f6b8214121)

**Comment by saschafoerster** [comment]
How about using fontawesome for the icons? Like this one? https://fontawesome.com/icons/facebook-square?s=brands

**Comment by rlafuente** [comment]
Indeed that's the plan! For the spec we mocked it up manually using the assets from Fontawesome, but they'll look much more in place when we implement it in the frontend.

**Comment by aiscarvalho** [comment]
After some exchange we decided to make the sharing into a expandable section instead of a popup. The [spec is updated](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4ac1a360-d117-11ec-b5d3-b772d2e677f5&section=interactions&index=2&share-id=68256310-d757-11ec-ab9e-75f6b8214121).

![image](https://user-images.githubusercontent.com/122730/169350154-3945bd41-047c-4269-b217-46caa2a2eed8.png)
