### ISSUE TITLE
Wireframe: Import contacts

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#203]
The wireframe for importing contacts is ready for review and feedback. Below is a short explanation of the flow and each screen.
[See it all in penpot](https://design.penpot.app/#/view/118239b0-dcf8-11ec-9f2d-f940e3befd53?page-id=4e29b270-b03a-11ec-8735-b3cbc25196fd&section=interactions&index=11&share-id=4e8b08c0-e5a2-11ec-9a7f-f940e3befd53).

**Step 1:** upload a file
![image](https://user-images.githubusercontent.com/122730/172423236-e0ad4cf0-c29e-4825-b6b3-090802471446.png)
![image](https://user-images.githubusercontent.com/122730/172423374-c4b4fb71-e712-4f09-81fe-8b925151983b.png)

----
**Step 1:** get help from the support team
![image](https://user-images.githubusercontent.com/122730/172423448-0d1ef071-d886-4c80-904d-da8ebf547567.png)

----
**Step 2:** map columns and batch tag imported contacts
![image](https://user-images.githubusercontent.com/122730/172423526-ce0a1681-0ab9-40c4-a9a9-fbcbdd8d3bb5.png)

----
**Step 2 extra:** review entries with missing data and possible duplicates
![image](https://user-images.githubusercontent.com/122730/172423684-d371f010-7b1b-463b-89bc-a9a930d213db.png)

----
**Step 3:** preview contacts to import and finish
![image](https://user-images.githubusercontent.com/122730/172423874-dbf3918c-e9d8-4233-a0d0-5b115d849923.png)

----
**Finished import successfully** - in this screen, we added a "duplicate finder" in the filter column (tentative place for a new feature)
![image](https://user-images.githubusercontent.com/122730/172424101-27c2e8fe-ad7f-4af5-95f7-df440f5840e4.png)

----
**Navigate to new filter:** imported contacts are added to a new filter (or segment), automatically named with the import date. The admin can rename this filter or delete it:
![image](https://user-images.githubusercontent.com/122730/172424194-62910b90-29bd-476c-918f-017f55bd04ae.png)

**Comment by wpf500** [comment]
Woo importing contacts!!

A few comments:
* In the requirements session @aiscarvalho suggested asking if the admin is just importing contacts or members with contributions, with the short term solution being that if they try to import members it points them towards the guided import. This feels quite important as the difference between just importing some contacts versus members with contributions, expiry dates etc. is significant. Could you wireframe this?
* Guided session booking will (at least initially) just be a Calendly embed so that can be left as an empty embed box in the design stage
* In the review stage we discussed showing updates to existing contacts and inserting new contacts separately, could this be added to the wireframe?
* The step 2 extra wireframe is probably mostly beyond the scope of the initial implementation. I would love to at least bring in the incomplete entries/problems detected bit, but possibly just to show which contacts won't be imported rather than in place editing as it feels like that could quickly become a complicated feature. What do you think?
* I like the idea of the duplicate finder, interested to explore that further in the future.

**Comment by aiscarvalho** [comment]
Thanks for the feedback!   
Here are the screenshots of the updated wireframes:

**_Step 0_**: ask the admin if the contacts to import contain payment data or not:
![image](https://user-images.githubusercontent.com/122730/173556476-3c30883b-faed-49ba-b7ff-c2372084e691.png)

If the contacts have payment data, redirect admin to book a support session (same as if guided import is selected):
![image](https://user-images.githubusercontent.com/122730/173556771-64f7ef49-7af3-4cf4-a4cc-bcd17a1e7281.png)

**Step 2 extra:** show contacts with matching emails and ask the admin if they should be updated or ignored; show entries with errors
![image](https://user-images.githubusercontent.com/122730/173556046-22d7f74e-4059-4266-aff8-4e1736dfaed3.png)

**Step 3**: preview changes to existing contacts + new contacts before finalizing the import
![image](https://user-images.githubusercontent.com/122730/173556978-08af6c9a-8ba5-428f-88db-5433bc7a4243.png)

**Comment by wpf500** [comment]
LGTM :+1:

**Comment by TobiasHauswurz** [comment]
Nothing to add, looks very good
