### ISSUE TITLE
Select responses from table and apply action (tag, bucket, etc.)

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#350]
Proposal for table actions using response table as an example.

Marking a response as verified (subtle difference in pagination between screens proposing to drop pagination when we have few table entries):

![image](https://user-images.githubusercontent.com/122730/214357664-97b54d1f-031e-43c0-8231-5bb347b1b6c9.png)
![image](https://user-images.githubusercontent.com/122730/214358288-f2f7750e-32d9-497d-b72e-e61ba0f148cb.png)

Tagging a response - we weren't sure about how we should handle tag creation here (managing tags in a different place vs managing tags in the same page):

![image](https://user-images.githubusercontent.com/122730/214358380-1eb8806e-25f8-4cd0-a423-98d04a7cccdb.png)
![image](https://user-images.githubusercontent.com/122730/214358424-16bc1c46-e948-441b-8323-5e55231dbcb1.png)

Alternative action buttons with text labels - we'd favor the icon buttons since it allows us to have space for more actions

![image](https://user-images.githubusercontent.com/122730/214360223-233fbfc2-e242-4c72-a12b-4f19ecb3ce3e.png)

General notes on table actions:
- the notifications can be used to show if an action was or wasn't successful
- in this example, we might need extra actions to "un-verify responses" and rescue responses from the trash
- in the _trashed responses_, selecting trash would result in deleting responses permanently
- in the spec only one table entry is selected but actions should work as bulk (multiple table entries selected)
 
[Penpot link](https://design.penpot.app/#/view/4755a563-5b43-8015-8001-e4e6b00d6e7d?page-id=4755a563-5b43-8015-8001-e4e6b00d6e7e&section=interactions&index=4&share-id=2a21f5ae-60ee-8151-8001-f461579125b9)

**Comment by wpf500** [comment]
I like the separation of actions on the left and filtering on the right, even if the actions only have icons). However I'm not sure how this layout works with a more complex table, e.g. contacts table, when there are filters to be shown and other things. If I was to implement this as is now it would look something like this:

![image](https://user-images.githubusercontent.com/2084823/214542503-2594be83-94dc-45c9-996a-31eec8c3820b.png)

Which I think is a bit confusing, which I guess is mostly because of the filtering/segments.

In general I think we need the following above the table:
* Filters
* Actions
* Number of results 
* Pagination? (I'd say yes)
* Page size? (I'd say no)

There are different types of actions:
* Applies to all results, e.g. Save segment
* Applies to all results or selection, e.g. Export, Send email
* Applies to selection, e.g. Tag, Delete

How do we show all these things together?! I tried doing a mock up to and it made me think that the problem is really how the filtering is displayed, the actions and selection you designed works well.

![image](https://user-images.githubusercontent.com/2084823/214543588-6ad1feb7-56d2-408c-ac3b-56282faf7c95.png)

What do you think? Does the above look okay? Sorry that's a bit of a brain dump in the end!

**Comment by wpf500** [comment]
It makes me think a bit of that mock up we did once around trying to make it clearer that the filters and advanced search were connected:

![image](https://user-images.githubusercontent.com/2084823/214544649-c3d911fe-650d-44cb-8773-97f74d3a6731.png)

**Comment by aiscarvalho** [comment]
[Penpot spec updated](https://design.penpot.app/#/view/4755a563-5b43-8015-8001-e4e6b00d6e7d?page-id=d5852c56-05c0-8062-8001-f58f75d37774&section=interactions&index=0&share-id=4755a563-5b43-8015-8001-f5928fe85b10)

Here is a sequence showing how to move a response to "verified", with an updated layout for search, filters, action buttons and pagination:

![image](https://user-images.githubusercontent.com/122730/214890272-25dae7f8-b3b4-47d2-8289-5994993305a0.png)
![image](https://user-images.githubusercontent.com/122730/214890339-c9a14e32-0c79-44c9-a131-ec960bbbbbc8.png)
![image](https://user-images.githubusercontent.com/122730/214890390-bfa60507-b5f6-4e3d-b7bf-cf4de1e91e7a.png)
![image](https://user-images.githubusercontent.com/122730/214890521-8aa9aec8-6021-43ae-88e0-f9ac13433a8e.png)

Layout with the filter UX experiments from your last comment (I just didn't update the order of search box with filters on the left side) -- **these screenshots were updated for clarity, see next comment or penpot**:
![image](https://user-images.githubusercontent.com/122730/214890728-774a341a-24c3-4ee0-85d8-2c80ea7998a4.png)
![image](https://user-images.githubusercontent.com/122730/214890794-53c0c887-6750-4b16-8c51-356a68033af8.png)

Updated:
- search and filters are shown first; if there are active filters we show the filter summary + save segment button
- action buttons below search: move to... list of buckets; tag... list of tags; export (exports selected table entries!)
- show editor comment checkbox to make last comment visible in table of callout responses
- shorter version of the table pagination (full pagination is shown at the bottom of the table)

We moved the save segment button to save space; and added the export as an action the table as it becomes more versatile.

Thanks for all the feedback so far!

**Comment by wpf500** [comment]
Looks good.

I'm not sure what the interaction is between the filter summary and the expanded search is. Your screenshot shows different filters in the summary compared to the expanded search, so presumably it updates when the user presses search?

I think this can go into review as it solves the original purpose of the card and the filters at least fit nicely with it now. Further UX improvements to the filters can happen in the future.

:+1:

**Comment by aiscarvalho** [comment]
Great!

The screenshot shows different filters in the summary and the expanded view by accident. I copy/pasted a different bit from the advanced search spec.
I updated the spec so filters match and the UX is clearer (also fixed the position of the _filters_ button, on the right of the search box):

![image](https://user-images.githubusercontent.com/122730/216010057-b599fcb7-fa6b-4e5a-b358-b918c1476ccf.png)
![image](https://user-images.githubusercontent.com/122730/216010093-cdc2f7e3-c26e-4ecb-929b-9af2e14745ee.png)

I'm adding a note to the previous comment (for the review).
