### ISSUE TITLE
Spec for "Show options" in tables

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#423]
Callout responses table page with an updated layout for table actions, options, general callout response settings (managing tags, folders and reviewers). In this layout "show latest comment" and "show answer to" are visible.

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/356c0808-d802-42ba-82e7-4608b4c0b602)

Alternative layout: "show latest comment" and "show answer to" inside a new button:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/a979be17-745f-4766-81c2-508e64659fb5)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/b2b6a209-b05a-48b7-9807-0b5d6746d9b9)

 Contacts and Callouts pages with the updated table options:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/2b6edfc6-6787-408f-8166-f9883eca97c8)
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/103a3946-b787-4d66-b565-5412f4bb7bd0)
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/bb4ed408-6fb6-4739-9cd6-c8d5d4657518)

[Penpot spec](https://design.penpot.app/#/view/4755a563-5b43-8015-8001-e4e6b00d6e7d?page-id=d563008f-be2f-80c3-8002-b410bba8e804&section=interactions&index=0&share-id=2ce020ae-2ffc-8057-8002-bd223685c320)

**Comment by TobiasHauswurz** [comment]
@aiscarvalho @rlafuente I love the new design, such an improvement. I think those two rows make total sense and like the design with the white background. 

One thing I'm wondering about, but not sure if it makes sense to mention it here: 

Tagging always involves a lot of effort. The option to set up tags on Will's response page was a great improvement over setting up tags in the contact list. However, I wonder whether it shouldn't be possible to assign and set up tags directly in the table instead of always having to take a diversion via a separate menu.

**Comment by wpf500** [comment]
This is much better :+1:

I'm not sure if I prefer the consolidated view options or the separate show and columns bit, I think we can try it and see which is nicer. I guess on mobile the show options would need to be collapsed in any case but it's nice if they can be open on desktop.

I like how the Filters being clearly separate to the "Search..." inputs makes it clear that the latter is searching within the filtered results, but still have some concerns about the interaction between them. Is it just confusing to have both Filters and "Search..." or is it okay?

Also what happens when there are multiple "quick search" options? For example the responses needs:
* "Search responses..." - full text search of a response
* "Tagged with..." - responses tagged with a specific tag
* "Assigned to..." - responses assigned to a user

Finally, I wonder if the table actions (tag, export, etc.) are a bit far away from the table? It feels a bit to me like it's not clear that if you select a few responses from the table then that affects the actions (e.g. it would only export the selected ones)

**Comment by aiscarvalho** [comment]
@wpf500 we revised the table options:
- moved the actions closer to the table, we agree it's ideal to have them closer
- include the callout responses quick filters (tagged with, assigned to)
- updated the search box to allow search by tag, response, assignee, or other
- changed _View options_ to _Table options_
- included the column selector in the table header

Regarding filters and search, we think they become clearer with this separation in different rows. We think filters still make sense though they're more of a power user tool ((they're specially useful for segmenting contacts).

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/9cc22996-73d3-4417-970a-8400dfe9bf20)

**Comment by wpf500** [comment]
Looks great to me :+1:.

The only thing is I don't think we can make the buttons that small, for accessibility reasons it's recommended to have a minimum of [44px x 44px touch target](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html). Some of our buttons are already a bit small but I'd rather not add to that. But I think we can sign off the design and I'll change it for the implementation.
