### ISSUE TITLE
Spec for callout slide editor

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#428]
This one was tricky, finding a sane layout to accomodate all the small parts was a challenge.

Some open questions that we can discuss over a quick call:

- We've kept the ability to edit the "Back" and "Next" buttons but removed the toggle to hide them. If this is needed we can put it back in, but it seems very brittle in terms of UX (esp. denying the user the ability to go back at any point in the form)
- Still on the Back/Next buttons, our idea was to have them as `contentEditable` so that the text can be changed in-place
- Depending on the importance of the slide title in the process, it's probably worth reviewing whether it should have a more discreet placement

## Desktop view

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/159868/c3557b12-cd98-4863-8ac9-636d82319378)

## View for narrow desktop screens

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/159868/2f5ba7f4-fb51-416e-9ff1-41d1586780d4)

## Penpot spec

[link](https://design.penpot.app/#/workspace/887044a0-9c39-11eb-b4cd-81aaa3a367f9/8ec95363-4e2c-80a4-8002-c5f3f83d1ba6?page-id=8ec95363-4e2c-80a4-8002-c5f3f83d1ba7)

**Comment by TobiasHauswurz** [comment]
Hey @rlafuente & @aiscarvalho,

I think it's a great approach. But it looks a bit like we have space problems, especially because of the bar on the left. What I like about the CNR design is that it really looks and feels like PowerPoint because that's the logic behind it. We've probably made general decisions against it, but I think it would be a good idea to have the slide editor in its own window so that it fills up all the space. Or maybe by making the sidebar collapsed, even on larger screens?

Some feedback on details: 

- I'm not sure about the double-click to edit buttons. We don't use that anywhere else in the system, do we?

- I would add the numbers at the "linked slide" indicator for big screens as well, like you do in the small screen version. It makes it much easier to recognize the right slide to link to next

- Maybe that will be a spec on its own, but I think there is a lot of complexity missing, especially when it comes to linking slides and choosing different paths. The CNR has the option to link different slides to different options (see screenshot). Is that something we should think about from the start? 

About your open questions: 

_- We've kept the ability to edit the "Back" and "Next" buttons but removed the toggle to hide them. If this is needed we can put it back in, but it seems very brittle in terms of UX (esp. denying the user the ability to go back at any point in the form)._

> I think it's important to be able to hide the buttons. Sometimes you don't want to have a Next button because the answer to a question should determine what the next slide is. Like in the screenshot for example. In that case, there is no need for a Next button. But I agree that it is less important with the back button. Or won't we have those buttons anyway @wpf500 ? Always thought they were very important to Marc. 
<img width="1440" alt="Bildschirmfoto 2023-07-21 um 16 11 19" src="https://github.com/beabee-communityrm/beabee-frontend/assets/99893322/5c680aca-5e95-4781-8570-b34eb1542f25">
<img width="1437" alt="Bildschirmfoto 2023-07-21 um 16 14 49" src="https://github.com/beabee-communityrm/beabee-frontend/assets/99893322/12f5e584-6985-4554-a294-d2cf95526ec1">

**Comment by wpf500** [comment]
As we discussed in sprint planning, I agree we should revisit the callout editor in general but it's a bit beyond the scope of this card at the moment. I've shown this to Michel (from CNR) and he is happy with the revised layout and using numbers for the slides :+1:.

We also discussed switching to always having a next button and using a special radio component to control the target, Michel was happy with that.
