### ISSUE TITLE
Callout status in summary component

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#454]
The current callout status (open/ended) needs more visibility in the summary cards, so we took the chance to unclutter its layout while highlighting the status part. The responses button was moved to the right to correspond to the usual placement of a call to action, and (in our opinion) it also balances it into a more organised layout.

(please ignore the color differences between both versions! It's because we couldn't access dev. so we used demo. as reference.)

## Before

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/159868/f8b1f659-072b-458d-91f9-02e3b78ad00a)

## After

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/159868/4b1cd65b-afe6-47e7-8d77-73a4e11aa1b4)

**Comment by wpf500** [comment]
I think this looks much nicer but wasn't what I was expecting to see changed. We discussed reviewing how the callout page itself should look once it's finished, but maybe this has been addressed by #453?

**Comment by aiscarvalho** [comment]
We forgot to include this revised component in #453 since that spec is mostly on the user side.
Do you think it would make sense to merge it though?

We've added it as an improvement in the backlog so it doesn't get lost.
Also, [here's a link to the penpot spec](https://design.penpot.app/#/view/4a499800-872e-80e1-8002-faf45855668b?page-id=4a499800-872e-80e1-8002-faf45855668c&section=interactions&index=0&share-id=52961d58-0a92-80c2-8003-39da355cb248)

**Comment by wpf500** [comment]
I think it can stay separate to #453. Thanks for adding the implemention to the backlog, we can close this issue now :+1:
